### ISSUE TITLE
Maintenance Supply icon missing in help page

### ISSUE THREAD

**Issue by MrBazlow** [attrib/foxhole-map-annotate#13]
From discord user polosatiyk#6240

![image](https://github.com/attrib/foxhole-map-annotate/assets/67396813/8aff4a8a-95ad-4a51-b5e4-dfe78421e20c)

**Comment by attrib** [comment]
Fixed in https://github.com/attrib/foxhole-map-annotate/commit/f704dcc47ddd3a5c7c5aab2bf0fe229e680de1d6
